name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout g-ui
      uses: actions/checkout@v3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'liberica'
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Checkout g-api
      uses: actions/checkout@v4
      with:
        repository: umu-art/g-api
      
    - name: Build g-api
      run: chmod 777 ./build-client-api.sh && /bin/bash ./build-client-api.sh

    - name: Checkout g-ui
      uses: actions/checkout@v3
      
    - name: Build g-ui
      run: npm run build
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vikazeni/g-ui:latest

        
  sync-server:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo hi
      

