name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout g-ui
      uses: actions/checkout@v3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'liberica'
        
    - name: Use Node.js 21
      uses: actions/setup-node@v3
      with:
        node-version: 21
    
    - name: Checkout g-api
      uses: actions/checkout@v4
      with:
        repository: umu-art/g-api

    - name: Create api dir
      run: mkdir /home/runner/work/api
      
    - name: Build g-api
      run: chmod 777 ./build-client-api.sh && ./build-client-api.sh /home/runner/work/api
      
    - name: Checkout g-ui
      uses: actions/checkout@v3

    - name: Add api client
      run: cp -r /home/runner/work/api/client ./
  
    - name: Clean up
      run: rm -r ./node_modules && npm cache clean --force
      
    - name: Install g-ui deps
      run: npm install
      
    - name: Build g-ui
      run: npm run build
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vikazeni/g-ui:latest

        
  sync-server:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo hi
      

